http:
  timeout: 20
  verify_ssl: true
  user_agent: "Mozilla/5.0 (compatible; SQLScanner/2.0)"
  proxies:
    http: ${HTTP_PROXY}
    https: ${HTTPS_PROXY}

scanner:
  payload_file: data/payloads.txt
  db_detection: auto
  techniques:
    - error_based
    - blind
    - time_based
  api_definitions_file: "data/api_endpoints.yaml"
  additional_targets_file: "data/additional_targets.yaml"
  max_threads: 10 
  discovery:
    enabled: true 
    wordlist_file: data/common_paths.txt
    extensions_to_append: [".php", ".html", ".txt", ".bak", ".old", ""] 
    interesting_status_codes: [200, 201, 204, 301, 302, 307, 401, 403, 500]
login:
  enabled: true
  url: "http://localhost:8000/process.php"
  method: "POST"
  data:
    username: "admin"
    password: "admin123"
  success_criteria:
    status_codes: [200, 302]  # Chấp nhận 200 hoặc 302
    cookies: ["PHPSESSID"]    # Kiểm tra cookie phiên
    redirect_url: null        # Tùy chọn, ví dụ: "/dashboard.php"
scan_urls:
  - "http://localhost:8000/dashboard.php"
  - "http://localhost:8000/profile.php"